### ISSUE TITLE
New logo design for kuis otak cerdas

### ISSUE THREAD

**Issue by zdesign1** [faimasitumorang/kuisotakcerdas#1]
Hello, I want to contribute to the kuis otak cerdas project, and I have design a logo, if you like, i will send files.

![prov](https://user-images.githubusercontent.com/38174403/38463658-cd89b108-3b29-11e8-8e13-f84d51ab2702.png)

![different](https://user-images.githubusercontent.com/38174403/38464236-24e7ffe0-3b34-11e8-9ef1-41f3a9e4c902.png)

**Comment by faimasitumorang** [comment]
Hi zdesign1, thanks for the design, i love it, where can i get the logo?

**Comment by zdesign1** [comment]
You can download the logo on this link https://drive.google.com/open?id=14043e56lrLBzrp2B4CtSj5-q98Y0yq-m

**Comment by faimasitumorang** [comment]
Okay, i have downloaded it, i will add it to this project. Thanks you.
